config/routes.rb
Rails.application.routes.draw do
  
  get 'frascos/entregados' => 'frascos#entregados', :as => "frascos_entregados"
  get 'frascos/eliminar' => 'frascos#eliminar', :as => "frascos_eliminar"
  get 'frascos/no_retirados' => 'frascos#no_retirados', :as => "frascos_no_retirados"
  resources :frascos
  post 'frascos/update/:id/:idFra/:noRet(.:format)' => "frascos#update",  :as => "frascos_update"
  post 'frascos/destroy/:id/:idFra(.:format)' => 'frascos#destroy', :as => "frascos_destroy"

  namespace :administrator do
    resource :pacientes do
       collection do
             get :buscar
             get :buscar_paciente
       end
    end   

    namespace :menu_nivel0 do
      resources :menu_nivel1s
    end
    
    resources :pacientes
    resources :configurations
    resources :tips
    resources :faqs
    resources :menu_nivel0s
    resources :contactos, only: [:index, :edit, :update, :destroy]

   # get 'pacientes/buscar', :to => 'pacientes#buscar'
  end


namespace :paciente do
 #  get 'pacientes' => 'pacientes#index', :as => "paciente"
end

#get 'administrator/home/index' => 'administrator/home#index', :as => "admin"

 
devise_scope :usuario do
  get 'usuarios' => 'registrations#show', :as => "usuario_registration"
  get 'usuarios/index', :to => 'registrations#index', :as => :usuarios_list
  get 'adminHome', :action => 'adminHome', :controller => 'registrations', :as => 'adminHome'

  get 'registrations/pacientes/:id/edit' => 'registrations#editPaciente', :as => "edit_paciente_registration"
  patch 'registrations/pacientes(.:format)'=> "registrations#update"
  put 'registrations/pacientes(.:format)'=> "registrations#update"


put 'usuarios/pacientes(.:format)'=> "registrations#update"
##'usuarios/edit_paciente', :to => 'registration#edit_paciente'
end

#patch 'registrations/editPaciente/:id(.:format)'=> "registrations#update"


devise_for :usuarios, controllers: {registrations: "registrations", sessions: "sessions"}
  
mount Ckeditor::Engine => '/ckeditor'

  devise_scope :usuarios do
    get 'usuarios/edit_paciente', :to => 'registration#edit_paciente'
  end

#resources :usuarios, only: [:index]

resource :usuario, only: [:edit] do
  collection do
    patch 'update_password'
  end
end

#resources :cambiar_passwords, only: [:edit, :update]

#devise_scope :usuario do
#  get '/passwordusuarios/edit(.:format)' => "passwordusuarios#edit", :as => :cambiar_password
#  patch '/passwordusuarios/(.:format)'=> "passwordusuarios#update"
#  put '/passwordusuarios/(.:format)'=> "passwordusuarios#update"
#end

get '/patients/:id', to: 'patients#show', as: 'patient'


resource :inbox, :controller => 'inbox', :only => [:show,:create]

PagesController.action_methods.each do |action|
  if action!="faq" && action!="tip" && action!="contacto" && action!="opcionPrincipal" 
  get "pages/contenido", to: "pages#contenido", as: "#{action}"
  end
end

get 'pages/faq' => 'pages#faq', as: :faq
get 'pages/tip' => 'pages#tip', as: :tip
#get 'pages/contacto' => 'pages#contacto', as: :contacto

scope '/pages' do
  resources :contactos, only: [:new, :create, :show]
end

get 'administrator/home/index' => 'administrator/home#index', :as => "admin"
get 'paciente/home/index' => 'paciente/pacientes#index', :as => "paciente"


root 'pages#home'



#nuevas rutas del proyecto para la materia
get 'ejemplo1' => 'paciente/pacientes#index'


end

app/models/administrator.rb
module Administrator
  def self.table_name_prefix
    'administrator_'
  end
end

app/models/administrator/configuration.rb
class Administrator::Configuration < ActiveRecord::Base
  belongs_to :usuario

  validates :nombre, presence: { message: "Debe colocar un nombre que describa a la imagen" }

  validates :nombre, length: {in: 5..50, 
            too_short: "Debe tener al menos 5 caracteres", 
            too_long: "No debe exceder de 20 carácteres"}

  validates :imagen1, presence: { message: "Debe colocar la ruta de la imagen que desea agregar" }

  #la siguiente linea se coloco en comentario para no usar
  #la función de Amazon S3 ya desarrollada, las fotos se colocan por photobucker
            
  #mount_uploader :imagen1, Imagen1Uploader

  #mount_uploader :imagen2, Imagen2Uploader
  #mount_uploader :imagen3, Imagen3Uploader
  #mount_uploader :imagen4, Imagen4Uploader
  #mount_uploader :imagen5, Imagen5Uploader


def extension_white_list
  %w(jpg jpeg gif png)
end

end

app/controllers/administrator/configurations_controller.rb
class Administrator::ConfigurationsController < ApplicationController
include CodigosGenerales

#la siguiente linea permite controlar que el usuario este logueado sino redirige a la 
#pagina de inicio de sessión 
before_filter :authenticate_usuario!

before_action :verificar_perfil_administrador

before_action :cargarOpcionesDelPrincipal
  
  before_action :set_administrator_configuration, only: [:show, :edit, :update, :destroy]
  before_action :calcular_cantidad_imagen_carrucel, only: [:new]
  layout "administrator"

  # GET /administrator/configurations
  # GET /administrator/configurations.json
  def index
    @administrator_configurations = Administrator::Configuration.all
    if @administrator_configurations.empty?
       flash.now[:warning] = "Aún no se han agregado imagenes al carrucel" 
     end
  end

  # GET /administrator/configurations/1
  # GET /administrator/configurations/1.json
  def show
    @cantidad = Administrator::Configuration.all.length
  end

  # GET /administrator/configurations/new
  def new
    @cantidad = Administrator::Configuration.all.length
    @administrator_configuration = Administrator::Configuration.new
  end

  # GET /administrator/configurations/1/edit
  def edit
    @carrucel = Administrator::Configuration.find( params[:id] )
  end

  # POST /administrator/configurations
  # POST /administrator/configurations.json
  def create
    @administrator_configuration = Administrator::Configuration.new(administrator_configuration_params)
    @administrator_configuration.usuario_id = current_usuario.id
      puts "en el create"
      @cantidad = Administrator::Configuration.all.length

    respond_to do |format|
      if @administrator_configuration.save
        puts "CREATE save"
        format.html { redirect_to @administrator_configuration, 
                      notice: 'La imagen fue agregada exitosamente.' }
        format.json { render :show, status: :created, location: @administrator_configuration }
      else
        @administrator_configuration.errors.each do |attr,msg| 
          puts msg if @administrator_configuration.errors[attr].first == msg 
        end                      
        format.html { render :new }
        format.json { render json: @administrator_configuration.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /administrator/configurations/1
  # PATCH/PUT /administrator/configurations/1.json
  def update
    @carrucel = Administrator::Configuration.find( params[:id] )
    #puts Administrator::Configuration.find( params[:id] )
    #puts administrator_configuration_params
    respond_to do |format|
      if @administrator_configuration.update(administrator_configuration_params)
        format.html { redirect_to @administrator_configuration,
                      notice: 'La imagen fue actualizada exitosamente' }
        format.json { render :show, status: :ok, location: @administrator_configuration }
      else
        format.html { render :edit }
        format.json { render json: @administrator_configuration.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /administrator/configurations/1
  # DELETE /administrator/configurations/1.json
  def destroy
    @administrator_configuration.destroy
    respond_to do |format|
      format.html { redirect_to administrator_configurations_url, notice: 'La imagen del carrucel fue eliminada exitosamente' }
      format.json { head :no_content }
    end
  end

  private

    def calcular_cantidad_imagen_carrucel
      puts "calcular_cantidad_imagen_carrucel"
 @imagenes = Administrator::Configuration.all.length
    end  

    # Use callbacks to share common setup or constraints between actions.
    def set_administrator_configuration
      @administrator_configuration = Administrator::Configuration.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def administrator_configuration_params
      params.require(:administrator_configuration).permit(:nombre, :enlace, :titulo_mensaje, :mensaje, :mensaje_visible, :imagen1, :imagen2, :imagen3, :imagen4, :imagen5, :usuario_id)
    end
end

app/controllers/administrator/contactos_controller.rb
class Administrator::ContactosController < ApplicationController
# before_action :cargarOpcionesDelPrincipal
before_action :verificar_perfil_administrador
include CodigosGenerales
layout :colocar_layout

def index
	@contactos = Contacto.where('respuesta' => nil).order('created_at desc')
end

def edit
  @contacto = Contacto.find(params[:id])
end

def update
  @contacto = Contacto.find params[:id]
  @contactos = Contacto.all.order('created_at desc')
  respond_to do |format|
    if @contacto.update(contacto_params)
      format.html {redirect_to administrator_contactos_path, notice: 'La respuesta a la consulta fue enviada exitosamente' }
      format.json { render :show, status: :ok, location: @contacto }
    else
    	@erroresContacto = @contacto
      format.html { render :index }
      format.json { render json: @contacto.errors, status: :unprocessable_entity }
    end
  end
end

def destroy
    @contacto = Contacto.find params[:id]
    @contacto.destroy
    respond_to do |format|
      format.html { redirect_to administrator_contactos_path, notice: 'El mensaje fue eliminado exitosamente.' }
      format.json { head :no_content }
    end
end

private
 	def contacto_params
      params.require(:contacto).permit(:nombre, :email, :mensaje, :respuesta, :id)
  end
end

app/controllers/administrator/faqs_controller.rb
class Administrator::FaqsController < ApplicationController
include CodigosGenerales

#la siguiente linea permite controlar que el usuario este logueado sino redirige a la 
#pagina de inicio de sessión 
 before_filter :authenticate_usuario!
 
 before_action :cargarOpcionesDelPrincipal

before_action :verificar_perfil_administrador

#before_action :redirect_to_root, :if => :signed_in?

layout "administrator"

  def index
  	 @faqs = Faq.all.order('created_at desc')
     if @faqs.empty?
       flash.now[:warning] = "Aún no se han creado preguntas y respuestas" 
     end
  end

  def show
    @faq = Faq.find(params[:id])
  end

  def new
    @faq = Faq.new
  end

  def edit
    @faq = Faq.find( params[:id] )
  end

  def create
    @faq = Faq.new(faq_params)
    @faq.usuario_id = current_usuario.id
    respond_to do |format|
      if @faq.save
        format.html { redirect_to administrator_faq_path(@faq), notice: 'La pregunta fue creada exitosamente' }
        format.json { render :show, status: :created, location: @faq }
      else
        format.html { render :new }
        format.json { render json: @faq.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @faq = Faq.find params[:id]
    @faq.usuario_id = current_usuario.id
    respond_to do |format|
      if @faq.update(faq_params)
        format.html {redirect_to administrator_faq_path(@faq), notice: 'La pregunta fue modificada exitosamente' }
        format.json { render :show, status: :ok, location: @faq }
      else
        format.html { render :edit }
        format.json { render json: @faq.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @faq = Faq.find params[:id]
    @faq.destroy
    respond_to do |format|
      format.html { redirect_to administrator_faqs_path(@faq), notice: 'La pregunta fue eliminada exitosamente.' }
      format.json { head :no_content }
    end
  end

  private
    def set_faq
      @faq = Faq.find(params[:id])
    end

 	def faq_params
      params.require(:faq).permit(:pregunta, :respuesta)
  end
end

app/controllers/administrator/home_controller.rb
class Administrator::HomeController < ApplicationController
include CodigosGenerales

#la siguiente linea permite controlar que el usuario este logueado sino redirige a la 
#pagina de inicio de sessión 
before_filter :authenticate_usuario!

before_action :verificar_usuario_autenticado

before_action :verificar_perfil_administrador

 before_action :cargarOpcionesDelPrincipal

layout :colocar_layout

def index
	@contactos = Contacto.where('respuesta' => nil)
end

def cargarOpcionesDelPrincipal
  @opcionesMenu = Administrator::MenuNivel0.all
  @opcionesSubMenu = {}
  @opcionesMenu.each do |opcion|
    enlace = opcion.enlace
    @valores = Administrator::MenuNivel0::MenuNivel1.where(administrator_menu_nivel0_id: opcion.id).order('posicion asc') 
    @opcionesSubMenu.merge!(enlace => @valores )
 end  
end

private 

def verificar_usuario_autenticado
	
	if current_usuario
	  if current_usuario.rol != 1 && current_usuario.rol != 2 && current_usuario.rol != 3	
		redirect_to new_usuario_session_path
	  end 	
	end  	
end

end

app/controllers/administrator/home_tratamiento_controller.rb
class Administrator::HomeTratamientoController < ApplicationController
include CodigosGenerales
# before_action :cargarOpcionesDelPrincipal
 
before_action :verificar_perfil_administrador
 
layout :colocar_layout

def index
	if current_usuario
	  if current_usuario.rol = 1 	
		opcionesmenu = Administrator::MenuNivel0.all.order('id asc')
	  end
	  if current_usuario.rol = 2

	  end	
	else
		redirect_to new_usuario_session_path
	end 	
end

private

def colocar_layout
	if current_usuario.rol == 1 
	  "administrator"	
	else 
	  if current_usuario.rol = 2 
	   "tratamiento"
	  end
	end
end
end

app/controllers/administrator/menu_nivel0s_controller.rb
class Administrator::MenuNivel0sController < ApplicationController
include CodigosGenerales

#la siguiente linea permite controlar que el usuario este logueado sino redirige a la 
#pagina de inicio de sessión 
before_filter :authenticate_usuario!

 before_action :cargarOpcionesDelPrincipal
  before_action :set_administrator_menu_nivel0, only: [:show, :edit, :update, :destroy]
  layout "administrator"
  
  # GET /administrator/menu_nivel0s
  # GET /administrator/menu_nivel0s.json
  def index
    @administrator_menu_nivel0s = Administrator::MenuNivel0.all
  end

  # GET /administrator/menu_nivel0s/1
  # GET /administrator/menu_nivel0s/1.json
  def show
  end

  # GET /administrator/menu_nivel0s/new
  def new
    @administrator_menu_nivel0 = Administrator::MenuNivel0.new
  end

  # GET /administrator/menu_nivel0s/1/edit
  def edit
  end

  # POST /administrator/menu_nivel0s
  # POST /administrator/menu_nivel0s.json
  def create

    @administrator_menu_nivel0 = Administrator::MenuNivel0.new(administrator_menu_nivel0_params)

    respond_to do |format|
      if @administrator_menu_nivel0.save
        format.html { redirect_to @administrator_menu_nivel0, notice: 'Menu nivel0 was successfully created.' }
        format.json { render :show, status: :created, location: @administrator_menu_nivel0 }
      else
        format.html { render :new }
        format.json { render json: @administrator_menu_nivel0.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /administrator/menu_nivel0s/1
  # PATCH/PUT /administrator/menu_nivel0s/1.json
  def update
    respond_to do |format|
      if @administrator_menu_nivel0.update(administrator_menu_nivel0_params)
        format.html { redirect_to @administrator_menu_nivel0, notice: 'Menu nivel0 was successfully updated.' }
        format.json { render :show, status: :ok, location: @administrator_menu_nivel0 }
      else
        format.html { render :edit }
        format.json { render json: @administrator_menu_nivel0.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /administrator/menu_nivel0s/1
  # DELETE /administrator/menu_nivel0s/1.json
  def destroy
    @administrator_menu_nivel0.destroy
    respond_to do |format|
      format.html { redirect_to administrator_menu_nivel0s_url, notice: 'Menu nivel0 was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_administrator_menu_nivel0
      @administrator_menu_nivel0 = Administrator::MenuNivel0.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def administrator_menu_nivel0_params
       params.require(:administrator_menu_nivel0).permit(
                :titulo, :tipo, :estado, :posicion, :enlace,
                :titulo_contenido, :contenido, :menu0_id)
    end
end

app/controllers/paciente/pacientes_controller.rb
class Paciente::PacientesController < ApplicationController
before_action :verificar_usuario_autenticado

include CodigosGenerales

#la siguiente linea permite controlar que el usuario este logueado sino redirige a la 
#pagina de inicio de sessión 
before_filter :authenticate_usuario!

layout :colocar_layout


def index
	@contactos = Contacto.where('respuesta' => nil)
end

private 
def verificar_usuario_autenticado
	
	if current_usuario
	  if current_usuario.rol != 1 && current_usuario.rol != 2 && current_usuario.rol != 3	
		redirect_to new_usuario_session_path
	  end 	
	end  	
end

end

app/helpers/admin/administrators_helper.rb
module Admin::AdministratorsHelper
end

app/helpers/administrator/configurations_helper.rb
module Administrator::ConfigurationsHelper
end

app/helpers/administrator/faq_helper.rb
module Administrator::FaqHelper
end

app/helpers/administrator/home_helper.rb
module Administrator::HomeHelper
def formatearOpcionMenu opcion
	opcion.sub("<br />", "")  
end
end

app/views/administrator/pacientes/_pacientes.html.erb
<%puts "VISTA _PACIENTES.HTML.ERB"%> 

<%if !flash.now[:alert].blank? %>

<div class="row">
  <div class="col-lg-12">
    <%# flash.each do |key, value| %>
    <div class="alert alert-success fade in">
      <a class="close" data-dismiss="alert" href="#">&times;</a>
      <strong><%#=value%><%=flash.now[:alert]%>
      </strong>
    </div><%# end %>
  </div>
</div><!-- /.row -->
<%end%>


<%if !@pacientes.nil? %>

<div class="table-responsive" style="height:360px"> 
  <table class="table table-striped table-hover" >
    <thead >
      <tr >
        <th>Número</th>
        <th>Cédula</th>
        <th>Apellido y Nombre</th>
        <th>E-mail</th>
        <th style="text-align: center">Ver</th>
        <th style="text-align: center">Editar</th>
        <th style="text-align: center">Eliminar</th>
      </tr>
    </thead>
    <tbody style="overflow-y: scroll;height: auto; width:100%">

     <% @pacientes.each_with_index do |paciente,i| %>
     <tr>
      <td><%=paciente.numero_excel%></td>
      <td><%=paciente.cedula%></td>
      <td><%=paciente.apellido + ", "+ paciente.nombre%></td>
      <td><%=paciente.email%></td>
      <td>
        <div align="center">
          <a data-toggle="collapse" data-parent="#accordion-<%=i.to_s%>" href="#collapse1-<%=i.to_s%>"><span class="fa fa-fw fa-search"></span></a>
        </div>
      </td>
      <td><%#= link_to edit_task_path(task), remote: true do %>
        <div align="center">
          <%=link_to edit_paciente_registration_path(paciente),
          title: 'Editar los datos del paciente',
          'data-toggle' => 'tooltip',
          'data-placement' => 'right' do %>
          <span class="fa fa-fw fa-pencil"></span>
          <%end%>
        </div>
      </td>
      <td>		
        <div align="center">
         <%=link_to  administrator_faq_path(paciente), method: :delete, 
         title: 'Eliminar el paciente',
         'data-toggle' => 'tooltip',
         'data-placement' => 'right',
         data: { confirm: 'Esta seguro que desea eliminar el paciente?' }  do %>
         <span class="fa fa-fw fa-trash-o"></span>
         <%end%>
       </div>

     </td>
   </tr>
   <%end%>
 </tbody>
</table>
</div>



<!--el siguiente código coloca la páginación sin estilos -->
<div id="page_links">
  <%#= paginate @pacientes %>
</div>

<!-- la siguiente instrucción carga la páginación con bootstrap-->

<div style="text-align:center">
  <%= js_will_paginate @pacientes, {page: params[:page], per_page: 5} %>
</div>
<!-- o también

<%#= js_will_paginate @pacientes %>


<%end%>


 

app/views/administrator/pacientes/buscar.html.erb
<div id="page-wrapper">
   <div class="container-fluid2">
   <%= render 'shared/dosFilasVistaShow', tituloVentana: "Buscar paciente en tratamiento"%>

      <div class="row" >       
          <div class="col-md-1"></div>
          <div class="col-md-10">         
          <div class="panel panel-primary" style="margin-bottom: 10px">
              <div class="panel-heading">
                <h3 class="panel-title"></h3>
                <div style="text-align: center"><h3 class="panel-title">Paciente a buscar </h3></div>
              </div>
              <div class="panel-body2">
                 <div class="list-group" style="margin-bottom: 1px">
						<!--se coloca el simbolo :paciente y no el objeto @paciente para que no use el modelo paciente -->
		               <%=simple_form_for(:paciente, remote: true, url: (buscar_administrator_pacientes_path), method: :get, html: { class: 'form-horizontal' }) do |f| %>

		<%#=simple_form_for(@contacto, url: (contactos_path), html: { class: 'form-horizontal' }) do |f| %>
							<%= f.error_notification %>
							<% if @paciente.errors.any? %>
								<div class="alert alert-danger">
								   <div class="error_explanation">
								      <ul>
								         <% @paciente.errors.each do |attr,msg| %>
								         <li><%= "#{msg}" if @paciente.errors[attr].first == msg %> </li>
								         <% end %>
								      </ul>
								   </div>
								</div>
							<% end %>
							<div class="form-group" style="margin-bottom:5px">
								<label class="control-label col-md-2" >*Dato a buscar:</label>
								<div class="col-md-7" style="height:1px">
									<%= f.input :datoBuscar, label: false, placeholder: "Coloque Número de cédula/nombre/apellido/email/número en tratamiento a buscar", wrapper_html: { class: 'username' } %>	
								</div>

								<div class="col-md-2">
									<div class="form-actions" align="center">
									 	  <%= f.button :submit, 'Buscar paciente', :class=> "btn-primary" %>
									</div>
								</div>
							</div>
					  <% end %>
                  </div>
                </div>
          </div>
          </div>
          <div class="col-md-1"></div>
         </div> <!-- /.row -->
       

<div id="loading-indicator" style="margin-bottom: 5px">
 <%= image_tag("ajax-loader.gif", :id => "loading-indicator", :style => "display:none") %>
</div>


<div class="row">
  <div class="col-md-10 col-md-offset-1" id="pacientes">
     <%#= render @pacientes %>
  </div>
</div>


 </div><!-- /.container-fluid -->
</div><!-- /#page-wrapper -->
        

app/views/administrator/pacientes/buscar.js.erb
<%puts "_BUSCAR"%>


<%#if @pacientes.present? %>
$('#pacientes').html("<%= escape_javascript(render('pacientes')) %>");
$('#pacientes').show();
<%#end%>