config/routes.rb
Rails.application.routes.draw do
  
  get 'frascos/entregados' => 'frascos#entregados', :as => "frascos_entregados"
  get 'frascos/eliminar' => 'frascos#eliminar', :as => "frascos_eliminar"
  get 'frascos/no_retirados' => 'frascos#no_retirados', :as => "frascos_no_retirados"
  resources :frascos
  post 'frascos/update/:id/:idFra/:noRet(.:format)' => "frascos#update",  :as => "frascos_update"
  post 'frascos/destroy/:id/:idFra(.:format)' => 'frascos#destroy', :as => "frascos_destroy"

  namespace :administrator do
    resource :pacientes do
       collection do
             get :buscar
             get :buscar_paciente
       end
    end   

    namespace :menu_nivel0 do
      resources :menu_nivel1s
    end
    
    resources :pacientes
    resources :configurations
    resources :tips
    resources :faqs
    resources :menu_nivel0s
    resources :contactos, only: [:index, :edit, :update, :destroy]

   # get 'pacientes/buscar', :to => 'pacientes#buscar'
  end


namespace :paciente do
 #  get 'pacientes' => 'pacientes#index', :as => "paciente"
end

#get 'administrator/home/index' => 'administrator/home#index', :as => "admin"

 
devise_scope :usuario do
  get 'usuarios' => 'registrations#show', :as => "usuario_registration"
  get 'usuarios/index', :to => 'registrations#index', :as => :usuarios_list
  get 'adminHome', :action => 'adminHome', :controller => 'registrations', :as => 'adminHome'

  get 'registrations/pacientes/:id/edit' => 'registrations#editPaciente', :as => "edit_paciente_registration"
  patch 'registrations/pacientes(.:format)'=> "registrations#update"
  put 'registrations/pacientes(.:format)'=> "registrations#update"


put 'usuarios/pacientes(.:format)'=> "registrations#update"
##'usuarios/edit_paciente', :to => 'registration#edit_paciente'
end

#patch 'registrations/editPaciente/:id(.:format)'=> "registrations#update"


devise_for :usuarios, controllers: {registrations: "registrations", sessions: "sessions"}
  
mount Ckeditor::Engine => '/ckeditor'

  devise_scope :usuarios do
    get 'usuarios/edit_paciente', :to => 'registration#edit_paciente'
  end

#resources :usuarios, only: [:index]

resource :usuario, only: [:edit] do
  collection do
    patch 'update_password'
  end
end

#resources :cambiar_passwords, only: [:edit, :update]

#devise_scope :usuario do
#  get '/passwordusuarios/edit(.:format)' => "passwordusuarios#edit", :as => :cambiar_password
#  patch '/passwordusuarios/(.:format)'=> "passwordusuarios#update"
#  put '/passwordusuarios/(.:format)'=> "passwordusuarios#update"
#end

get '/patients/:id', to: 'patients#show', as: 'patient'


resource :inbox, :controller => 'inbox', :only => [:show,:create]

PagesController.action_methods.each do |action|
  if action!="faq" && action!="tip" && action!="contacto" && action!="opcionPrincipal" 
  get "pages/contenido", to: "pages#contenido", as: "#{action}"
  end
end

get 'pages/faq' => 'pages#faq', as: :faq
get 'pages/tip' => 'pages#tip', as: :tip
#get 'pages/contacto' => 'pages#contacto', as: :contacto

scope '/pages' do
  resources :contactos, only: [:new, :create, :show]
end

get 'administrator/home/index' => 'administrator/home#index', :as => "admin"
get 'paciente/home/index' => 'paciente/pacientes#index', :as => "paciente"


root 'pages#home'



#nuevas rutas del proyecto para la materia
get 'ejemplo1' => 'paciente/pacientes#index'


end

app/models/administrator.rb
module Administrator
  def self.table_name_prefix
    'administrator_'
  end
end

app/models/administrator/configuration.rb
class Administrator::Configuration < ActiveRecord::Base
  belongs_to :usuario

  validates :nombre, presence: { message: "Debe colocar un nombre que describa a la imagen" }

  validates :nombre, length: {in: 5..50, 
            too_short: "Debe tener al menos 5 caracteres", 
            too_long: "No debe exceder de 20 carácteres"}

  validates :imagen1, presence: { message: "Debe colocar la ruta de la imagen que desea agregar" }

  #la siguiente linea se coloco en comentario para no usar
  #la función de Amazon S3 ya desarrollada, las fotos se colocan por photobucker
            
  #mount_uploader :imagen1, Imagen1Uploader

  #mount_uploader :imagen2, Imagen2Uploader
  #mount_uploader :imagen3, Imagen3Uploader
  #mount_uploader :imagen4, Imagen4Uploader
  #mount_uploader :imagen5, Imagen5Uploader


def extension_white_list
  %w(jpg jpeg gif png)
end

end

app/models/administrator/menu_nivel0.rb
class Administrator::MenuNivel0 < ActiveRecord::Base
has_many :administrator_menu_nivel0_menu_nivel1s, :class_name => '::Administrator::MenuNivel0::MenuNivel1'
#self.table_name = 'administrator_menu_nivel0s'
end

app/controllers/administrator/configurations_controller.rb
class Administrator::ConfigurationsController < ApplicationController
include CodigosGenerales

#la siguiente linea permite controlar que el usuario este logueado sino redirige a la 
#pagina de inicio de sessión 
before_filter :authenticate_usuario!

before_action :verificar_perfil_administrador

before_action :cargarOpcionesDelPrincipal
  
  before_action :set_administrator_configuration, only: [:show, :edit, :update, :destroy]
  before_action :calcular_cantidad_imagen_carrucel, only: [:new]
  layout "administrator"

  # GET /administrator/configurations
  # GET /administrator/configurations.json
  def index
    @administrator_configurations = Administrator::Configuration.all
    if @administrator_configurations.empty?
       flash.now[:warning] = "Aún no se han agregado imagenes al carrucel" 
     end
  end

  # GET /administrator/configurations/1
  # GET /administrator/configurations/1.json
  def show
    @cantidad = Administrator::Configuration.all.length
  end

  # GET /administrator/configurations/new
  def new
    @cantidad = Administrator::Configuration.all.length
    @administrator_configuration = Administrator::Configuration.new
  end

  # GET /administrator/configurations/1/edit
  def edit
    @carrucel = Administrator::Configuration.find( params[:id] )
  end

  # POST /administrator/configurations
  # POST /administrator/configurations.json
  def create
    @administrator_configuration = Administrator::Configuration.new(administrator_configuration_params)
    @administrator_configuration.usuario_id = current_usuario.id
      puts "en el create"
      @cantidad = Administrator::Configuration.all.length

    respond_to do |format|
      if @administrator_configuration.save
        puts "CREATE save"
        format.html { redirect_to @administrator_configuration, 
                      notice: 'La imagen fue agregada exitosamente.' }
        format.json { render :show, status: :created, location: @administrator_configuration }
      else
        @administrator_configuration.errors.each do |attr,msg| 
          puts msg if @administrator_configuration.errors[attr].first == msg 
        end                      
        format.html { render :new }
        format.json { render json: @administrator_configuration.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /administrator/configurations/1
  # PATCH/PUT /administrator/configurations/1.json
  def update
    @carrucel = Administrator::Configuration.find( params[:id] )
    #puts Administrator::Configuration.find( params[:id] )
    #puts administrator_configuration_params
    respond_to do |format|
      if @administrator_configuration.update(administrator_configuration_params)
        format.html { redirect_to @administrator_configuration,
                      notice: 'La imagen fue actualizada exitosamente' }
        format.json { render :show, status: :ok, location: @administrator_configuration }
      else
        format.html { render :edit }
        format.json { render json: @administrator_configuration.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /administrator/configurations/1
  # DELETE /administrator/configurations/1.json
  def destroy
    @administrator_configuration.destroy
    respond_to do |format|
      format.html { redirect_to administrator_configurations_url, notice: 'La imagen del carrucel fue eliminada exitosamente' }
      format.json { head :no_content }
    end
  end

  private

    def calcular_cantidad_imagen_carrucel
      puts "calcular_cantidad_imagen_carrucel"
 @imagenes = Administrator::Configuration.all.length
    end  

    # Use callbacks to share common setup or constraints between actions.
    def set_administrator_configuration
      @administrator_configuration = Administrator::Configuration.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def administrator_configuration_params
      params.require(:administrator_configuration).permit(:nombre, :enlace, :titulo_mensaje, :mensaje, :mensaje_visible, :imagen1, :imagen2, :imagen3, :imagen4, :imagen5, :usuario_id)
    end
end

app/controllers/administrator/contactos_controller.rb
class Administrator::ContactosController < ApplicationController
# before_action :cargarOpcionesDelPrincipal
before_action :verificar_perfil_administrador
include CodigosGenerales
layout :colocar_layout

def index
	@contactos = Contacto.where('respuesta' => nil).order('created_at desc')
end

def edit
  @contacto = Contacto.find(params[:id])
end

def update
  @contacto = Contacto.find params[:id]
  @contactos = Contacto.all.order('created_at desc')
  respond_to do |format|
    if @contacto.update(contacto_params)
      format.html {redirect_to administrator_contactos_path, notice: 'La respuesta a la consulta fue enviada exitosamente' }
      format.json { render :show, status: :ok, location: @contacto }
    else
    	@erroresContacto = @contacto
      format.html { render :index }
      format.json { render json: @contacto.errors, status: :unprocessable_entity }
    end
  end
end

def destroy
    @contacto = Contacto.find params[:id]
    @contacto.destroy
    respond_to do |format|
      format.html { redirect_to administrator_contactos_path, notice: 'El mensaje fue eliminado exitosamente.' }
      format.json { head :no_content }
    end
end

private
 	def contacto_params
      params.require(:contacto).permit(:nombre, :email, :mensaje, :respuesta, :id)
  end
end

app/controllers/administrator/faqs_controller.rb
class Administrator::FaqsController < ApplicationController
include CodigosGenerales

#la siguiente linea permite controlar que el usuario este logueado sino redirige a la 
#pagina de inicio de sessión 
 before_filter :authenticate_usuario!
 
 before_action :cargarOpcionesDelPrincipal

before_action :verificar_perfil_administrador

#before_action :redirect_to_root, :if => :signed_in?

layout "administrator"

  def index
  	 @faqs = Faq.all.order('created_at desc')
     if @faqs.empty?
       flash.now[:warning] = "Aún no se han creado preguntas y respuestas" 
     end
  end

  def show
    @faq = Faq.find(params[:id])
  end

  def new
    @faq = Faq.new
  end

  def edit
    @faq = Faq.find( params[:id] )
  end

  def create
    @faq = Faq.new(faq_params)
    @faq.usuario_id = current_usuario.id
    respond_to do |format|
      if @faq.save
        format.html { redirect_to administrator_faq_path(@faq), notice: 'La pregunta fue creada exitosamente' }
        format.json { render :show, status: :created, location: @faq }
      else
        format.html { render :new }
        format.json { render json: @faq.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @faq = Faq.find params[:id]
    @faq.usuario_id = current_usuario.id
    respond_to do |format|
      if @faq.update(faq_params)
        format.html {redirect_to administrator_faq_path(@faq), notice: 'La pregunta fue modificada exitosamente' }
        format.json { render :show, status: :ok, location: @faq }
      else
        format.html { render :edit }
        format.json { render json: @faq.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @faq = Faq.find params[:id]
    @faq.destroy
    respond_to do |format|
      format.html { redirect_to administrator_faqs_path(@faq), notice: 'La pregunta fue eliminada exitosamente.' }
      format.json { head :no_content }
    end
  end

  private
    def set_faq
      @faq = Faq.find(params[:id])
    end

 	def faq_params
      params.require(:faq).permit(:pregunta, :respuesta)
  end
end

app/controllers/administrator/home_controller.rb
class Administrator::HomeController < ApplicationController
include CodigosGenerales

#la siguiente linea permite controlar que el usuario este logueado sino redirige a la 
#pagina de inicio de sessión 
before_filter :authenticate_usuario!

before_action :verificar_usuario_autenticado

before_action :verificar_perfil_administrador

 before_action :cargarOpcionesDelPrincipal

layout :colocar_layout

def index
	@contactos = Contacto.where('respuesta' => nil)
end

def cargarOpcionesDelPrincipal
  @opcionesMenu = Administrator::MenuNivel0.all
  @opcionesSubMenu = {}
  @opcionesMenu.each do |opcion|
    enlace = opcion.enlace
    @valores = Administrator::MenuNivel0::MenuNivel1.where(administrator_menu_nivel0_id: opcion.id).order('posicion asc') 
    @opcionesSubMenu.merge!(enlace => @valores )
 end  
end

private 

def verificar_usuario_autenticado
	
	if current_usuario
	  if current_usuario.rol != 1 && current_usuario.rol != 2 && current_usuario.rol != 3	
		redirect_to new_usuario_session_path
	  end 	
	end  	
end

end

app/controllers/administrator/home_tratamiento_controller.rb
class Administrator::HomeTratamientoController < ApplicationController
include CodigosGenerales
# before_action :cargarOpcionesDelPrincipal
 
before_action :verificar_perfil_administrador
 
layout :colocar_layout

def index
	if current_usuario
	  if current_usuario.rol = 1 	
		opcionesmenu = Administrator::MenuNivel0.all.order('id asc')
	  end
	  if current_usuario.rol = 2

	  end	
	else
		redirect_to new_usuario_session_path
	end 	
end

private

def colocar_layout
	if current_usuario.rol == 1 
	  "administrator"	
	else 
	  if current_usuario.rol = 2 
	   "tratamiento"
	  end
	end
end
end

app/controllers/administrator/menu_nivel0s_controller.rb
class Administrator::MenuNivel0sController < ApplicationController
include CodigosGenerales

#la siguiente linea permite controlar que el usuario este logueado sino redirige a la 
#pagina de inicio de sessión 
before_filter :authenticate_usuario!

 before_action :cargarOpcionesDelPrincipal
  before_action :set_administrator_menu_nivel0, only: [:show, :edit, :update, :destroy]
  layout "administrator"
  
  # GET /administrator/menu_nivel0s
  # GET /administrator/menu_nivel0s.json
  def index
    @administrator_menu_nivel0s = Administrator::MenuNivel0.all
  end

  # GET /administrator/menu_nivel0s/1
  # GET /administrator/menu_nivel0s/1.json
  def show
  end

  # GET /administrator/menu_nivel0s/new
  def new
    @administrator_menu_nivel0 = Administrator::MenuNivel0.new
  end

  # GET /administrator/menu_nivel0s/1/edit
  def edit
  end

  # POST /administrator/menu_nivel0s
  # POST /administrator/menu_nivel0s.json
  def create

    @administrator_menu_nivel0 = Administrator::MenuNivel0.new(administrator_menu_nivel0_params)

    respond_to do |format|
      if @administrator_menu_nivel0.save
        format.html { redirect_to @administrator_menu_nivel0, notice: 'Menu nivel0 was successfully created.' }
        format.json { render :show, status: :created, location: @administrator_menu_nivel0 }
      else
        format.html { render :new }
        format.json { render json: @administrator_menu_nivel0.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /administrator/menu_nivel0s/1
  # PATCH/PUT /administrator/menu_nivel0s/1.json
  def update
    respond_to do |format|
      if @administrator_menu_nivel0.update(administrator_menu_nivel0_params)
        format.html { redirect_to @administrator_menu_nivel0, notice: 'Menu nivel0 was successfully updated.' }
        format.json { render :show, status: :ok, location: @administrator_menu_nivel0 }
      else
        format.html { render :edit }
        format.json { render json: @administrator_menu_nivel0.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /administrator/menu_nivel0s/1
  # DELETE /administrator/menu_nivel0s/1.json
  def destroy
    @administrator_menu_nivel0.destroy
    respond_to do |format|
      format.html { redirect_to administrator_menu_nivel0s_url, notice: 'Menu nivel0 was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_administrator_menu_nivel0
      @administrator_menu_nivel0 = Administrator::MenuNivel0.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def administrator_menu_nivel0_params
       params.require(:administrator_menu_nivel0).permit(
                :titulo, :tipo, :estado, :posicion, :enlace,
                :titulo_contenido, :contenido, :menu0_id)
    end
end

app/helpers/admin/administrators_helper.rb
module Admin::AdministratorsHelper
end

app/helpers/administrator/configurations_helper.rb
module Administrator::ConfigurationsHelper
end

app/helpers/administrator/faq_helper.rb
module Administrator::FaqHelper
end

app/helpers/administrator/home_helper.rb
module Administrator::HomeHelper
def formatearOpcionMenu opcion
	opcion.sub("<br />", "")  
end
end

app/views/administrator/contactos/_form.html.erb
<%=simple_form_for([:administrator, @contacto], url: administrator_contacto_path(@contacto)) do |f| %>

<%puts "FORM"%>
<%puts @contacto.to_yaml%> 

<%= f.error_notification %>

<ul class="list-group">
   <li class="list-group-item"><strong>Nombre del usuario:</strong>
   <%=@contacto.nombre%>
   </li>
    <li class="list-group-item"><strong>Fecha de la consulta:</strong>
   <%=@contacto.created_at.to_s(:custom_datetime)%>
   </li>
   <li class="list-group-item"><strong>Consulta:</strong>
   <%=@contacto.mensaje%>
   </li>
</ul>

<%= f.input :respuesta, as: :text, label: 'Respuesta', placeholder: "Coloque aquí la respuesta a la consulta del usuario", :input_html => {:style=> 'width: 100%;', :rows =>5} %>   


<div class="form-actions" align="center">
   <%= f.button :submit, 'Enviar respuesta', :class=> "btn btn-primary" %>
</div>
<% end %>

app/views/administrator/contactos/edit.html.erb
<div id="page-wrapper">
   <div class="container-fluid">
      <%= render 'shared/dosFilasVistas', tituloVentana: "Responder mensaje" %>
      <div class="row">
         <div class="col-lg-3"></div>
         <div class="col-lg-6">
            <div class="panel panel-primary">
               <div class="panel-heading">
                  <h3 class="panel-title"></h3>
                  <div style="text-align: center">
                     <h3 class="panel-title">Responder mensaje enviado por un usuario</h3>
                  </div>
               </div>
               <div class="panel-body">
                  <div class="list-group">
                     <%= render 'form'%>
                  </div>
                  
               </div>
            </div>
         </div>
         <div class="col-lg-3"></div>
         <!-- /.row -->

      </div>
               <div align="center">
                     <%= link_to "Regresar", administrator_contactos_path%>
                  </div>
      <!-- /.container-fluid -->
   </div>
   <!-- /#page-wrapper -->
</div>

app/views/administrator/contactos/index.html.erb
<div id="page-wrapper">
   <div class="container-fluid">
   <%= render 'shared/dosFilasVistaShow', tituloVentana: "Contactos por responder"%>


      <div class="row">
         <div class="col-lg-2"></div>
         <div class="col-lg-8">
            <div class="list-group">
               <a href="#" class="list-group-item active">
                  <div align="center">
                     <h4 class="list-group-item-heading">Citas médicas solicitadas</h4>
                  </div>
               </a>
            </div>
   <%if !@contactos.empty?%>

            <% @contactos.each_with_index do |contacto,i| %>
            <div class="panel-group">
               <div class="panel panel-info">
                  <div class="panel-heading">
                     <h4 class="panel-title">
                        <a data-toggle="collapse" data-parent="#accordion-<%=i.to_s%>" href="#collapse1-<%=i.to_s%>">
                        <%#= contacto.created_at.to_s(:custom_datetime)%> | 
                        <%= humanizarFecha contacto.created_at%>
                        <%#=contacto.nombre%></a>
                        <div class="pull-right">
                           <div class="controls">
                              <a data-toggle="collapse" data-parent="#accordion-<%=i.to_s%>" href="#collapse1-<%=i.to_s%>"><span class="fa fa-fw fa-search"></span></a>
                              <%=link_to edit_administrator_contacto_path(contacto),
                                 title: 'Responder mensaje',
                                  'data-toggle' => 'tooltip',
                                  'data-placement' => 'right' do %>
                              <span class="fa fa-fw fa-check-square-o"></span>
                              <%end%>
                              <%=link_to administrator_contacto_path(contacto), method: :delete, 
                                 title: 'Eliminar mensaje',
                                  'data-toggle' => 'tooltip',
                                  'data-placement' => 'right',
                                  data: { confirm: 'Esta seguro que desea eliminar la consulta enviada por el usuario?' }  do %>
                              <span class="fa fa-fw fa-trash-o"></span>
                              <%end%>
                           </div>
                        </div>
                     </h4>
                  </div>
                  <div id="collapse1-<%=i.to_s%>" class="panel-collapse collapse out">
                     <div class="panel-body">
                        <ul class="list-group">
                          <li class="list-group-item"><strong>Nombre del usuario:</strong>
                              <%=contacto.nombre%>
                           </li>
                            <li class="list-group-item">
                            <strong>Telefono local: </strong><%=contacto.telefono_celular%>
                            </li>
                            <li class="list-group-item">
                            <strong>Telefono celular: </strong><%=contacto.telefono_celular%>


                             </li>
                           <li class="list-group-item"><strong>E-mail del usuario:</strong>
                              <%=contacto.email%>
                           </li>
                           <li class="list-group-item"><strong>Consulta:</strong>
                              <%=contacto.mensaje%>
                           </li>
                        </ul>
                        <%=link_to "Responder", edit_administrator_contacto_path(contacto), class: 'btn btn-success'%>
                     </div>
                  </div>
               </div>
            </div>
            <%end%>
         </div>
<div class="row">
      <div class="col-lg-12">
   <div align="center">
      <%#= link_to "Regresar", admin_path, :class=> "btn btn-success" %>
      <%= link_to "Regresar", admin_path%>

   </div>
  </div>
</div>     
<%else%>
 <div class="row">
      <div class="col-lg-12">
          <div class="alert alert-warning fade in">
            <strong>No existen más mensajes por responder</strong>       
          </div>
      </div>
   <div align="center">
      <%= link_to "Regresar", admin_path, :class=> "btn btn-success" %>
   </div>
</div>

   <% end %>
  </div>
      <div class="col-lg-2"></div>
   </div>  
</div>
<!-- /.container-fluid -->
</div><!-- /#page-wrapper -->