config/routes.rb
Rails.application.routes.draw do
  
  get 'frascos/entregados' => 'frascos#entregados', :as => "frascos_entregados"
  get 'frascos/eliminar' => 'frascos#eliminar', :as => "frascos_eliminar"
  get 'frascos/no_retirados' => 'frascos#no_retirados', :as => "frascos_no_retirados"
  resources :frascos
  post 'frascos/update/:id/:idFra/:noRet(.:format)' => "frascos#update",  :as => "frascos_update"
  post 'frascos/destroy/:id/:idFra(.:format)' => 'frascos#destroy', :as => "frascos_destroy"

  namespace :administrator do
    resource :pacientes do
       collection do
             get :buscar
             get :buscar_paciente
       end
    end   

    namespace :menu_nivel0 do
      resources :menu_nivel1s
    end
    
    resources :pacientes
    resources :configurations
    resources :tips
    resources :faqs
    resources :menu_nivel0s
    resources :contactos, only: [:index, :edit, :update, :destroy]

   # get 'pacientes/buscar', :to => 'pacientes#buscar'
  end


namespace :paciente do
 #  get 'pacientes' => 'pacientes#index', :as => "paciente"
end

#get 'administrator/home/index' => 'administrator/home#index', :as => "admin"

 
devise_scope :usuario do
  get 'usuarios' => 'registrations#show', :as => "usuario_registration"
  get 'usuarios/index', :to => 'registrations#index', :as => :usuarios_list
  get 'adminHome', :action => 'adminHome', :controller => 'registrations', :as => 'adminHome'

  get 'registrations/pacientes/:id/edit' => 'registrations#editPaciente', :as => "edit_paciente_registration"
  patch 'registrations/pacientes(.:format)'=> "registrations#update"
  put 'registrations/pacientes(.:format)'=> "registrations#update"


put 'usuarios/pacientes(.:format)'=> "registrations#update"
##'usuarios/edit_paciente', :to => 'registration#edit_paciente'
end

#patch 'registrations/editPaciente/:id(.:format)'=> "registrations#update"


devise_for :usuarios, controllers: {registrations: "registrations", sessions: "sessions"}
  
mount Ckeditor::Engine => '/ckeditor'

  devise_scope :usuarios do
    get 'usuarios/edit_paciente', :to => 'registration#edit_paciente'
  end

#resources :usuarios, only: [:index]

resource :usuario, only: [:edit] do
  collection do
    patch 'update_password'
  end
end

#resources :cambiar_passwords, only: [:edit, :update]

#devise_scope :usuario do
#  get '/passwordusuarios/edit(.:format)' => "passwordusuarios#edit", :as => :cambiar_password
#  patch '/passwordusuarios/(.:format)'=> "passwordusuarios#update"
#  put '/passwordusuarios/(.:format)'=> "passwordusuarios#update"
#end

get '/patients/:id', to: 'patients#show', as: 'patient'


resource :inbox, :controller => 'inbox', :only => [:show,:create]

PagesController.action_methods.each do |action|
  if action!="faq" && action!="tip" && action!="contacto" && action!="opcionPrincipal" 
  get "pages/contenido", to: "pages#contenido", as: "#{action}"
  end
end

get 'pages/faq' => 'pages#faq', as: :faq
get 'pages/tip' => 'pages#tip', as: :tip
#get 'pages/contacto' => 'pages#contacto', as: :contacto

scope '/pages' do
  resources :contactos, only: [:new, :create, :show]
end

get 'administrator/home/index' => 'administrator/home#index', :as => "admin"
get 'paciente/home/index' => 'paciente/pacientes#index', :as => "paciente"


root 'pages#home'



#nuevas rutas del proyecto para la materia
get 'ejemplo1' => 'paciente/pacientes#index'


end

app/views/shared/_carrucel.html.erb
<div class="clearfix mar_top10"></div>

<!-- Carousel
   ================================================== -->
<div id="myCarousel" class="carousel slide" data-ride="carousel">
   <!-- Indicators -->
   <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
   </ol>
   <div class="carousel-inner" role="listbox">
    
<%if !@carrucel == nil %>
      <% @carrucels.each_with_index do |carrucel,i| %>

      <%=puts "VALOR I "+i.to_s%> 
      <div class="<%= i==0? 'item active' : 'item' %>">
         <%= image_tag carrucel.imagen1, :alt => "#{carrucel.nombre}", :title => "#{carrucel.nombre}"%>
         <div class="container">
            <div class="carousel-caption">
              <%if carrucel.mensaje_visible? %>
                 <%if !carrucel.titulo_mensaje.empty?%>
                    <h1><%=carrucel.titulo_mensaje%></h1>
                 <%end%> 
                 <%if !carrucel.mensaje.empty?%>                    
                    <p><%=carrucel.mensaje%></p>
                 <%end%>
              <%end%>   
            </div>
         </div>
      </div>
      <%end%>
<%end%>
     
   </div>
   <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
   <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
   <span class="sr-only">Previous</span>
   </a>
   <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
   <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
   <span class="sr-only">Next</span>
   </a>
</div>
<!-- FIN CARRUCEL
   ============================= -->

app/views/shared/_dosFilasVistaShow.html.erb
   <div class="row">
      <div class="col-lg-12">
        <h2 class="page-header" style="margin-bottom: 5px">
           Administración: <small><%=tituloVentana%></small>
        </h2>
      </div>
    </div>
    <!-- /.row -->  

   
<%if !flash.nil?%>
     <div class="row">
          <div class="col-sm-12">
            <% flash.each do |key, value| %>

            <div class="alert alert-success fade in">
              <a class="close" data-dismiss="alert" href="#">&times;</a>
              <strong><%=value%></strong>
            </div>
            <% end %>
          </div>
        </div><!-- /.row -->

<%end%>

app/views/shared/_dosFilasVistas.html.erb
      <!-- Page Heading -->

    <div class="row">
      <div class="col-lg-12">
        <h2 class="page-header">
           Administración: <small><%=tituloVentana%></small>
        </h2>
      </div>
    </div>
    <!-- /.row -->  

    <div class="row">
      <div class="col-lg-12">
        <% flash.each do |key, value| %>
                    <%puts key%>
            <%puts value%>
            <%if key == "notice"%>
              <div class="alert alert-success fade in">
            <%else%>
              <div class="alert alert-<%=key%> fade in">
            <%end%>
              <a class="close" data-dismiss="alert" href="#">&times;</a>
              <strong><%=value%></strong>
            </div>
               
        <% end %>
      </div>
    </div>
    <!-- /.row -->

app/views/shared/_footer.html.erb
<!-- Footer
======================================= -->

<div class="footer">
	<div class="container">
    
   		<div class="one_fourth">            
            
            <!-- end footer logo -->
            <ul  class="list">
            	 <h2>Dirección</h2>
                 <li><i class="fa fa-map-marker fa-lg"></i>
                 &nbsp;Urologíco San Roman, </li>
                 <li>&nbsp;&nbsp;&nbsp;&nbsp;Calle Chivacoa, </li>
                 <li>&nbsp;&nbsp;&nbsp;&nbsp;Sección San Román,</li>
				 <li>&nbsp;&nbsp;&nbsp;&nbsp;Urbanización las Mercedes,</li>
                 <li>&nbsp;&nbsp;&nbsp;&nbsp;Piso 1, consultorio 14.</li>

				 <li>&nbsp;&nbsp;&nbsp;&nbsp;Caracas - Distrito Capital. Venezuela.</li>
                  <li>&nbsp;&nbsp;&nbsp;&nbsp;Teléfono master:</li>
                <li>&nbsp;&nbsp;&nbsp;&nbsp;<i class="fa fa-phone"></i>&nbsp;(0212) 999.01.11</li>
                <li>&nbsp;&nbsp;&nbsp;&nbsp;<i class="fa fa-phone"></i>&nbsp;(0212) 992.22.22</li>
                <li>&nbsp;&nbsp;&nbsp;&nbsp;
                <%= image_tag "footer-wmap.png", :alt => "Image Footer"%>
                    </li>
            </ul>
            
        </div><!-- end address section -->
        
        <div class="one_third">        	
            <h2>Contacto</h2>            
            <ul class="list">             
                <li>Dr. Armando Antonio  Pérez Puigbo</li>
                <li>Dr(a). Susana Ferro</li>
                <li>Horario: Lunes a Viernes 7:00 am a 2:00 pm</li>
                <li>Teléfonos directos:</li>
                <li><i class="fa fa-phone"></i> (0212) 991.46.20 </li>
                <li><i class="fa fa-phone"></i> (0212) 999.01.53</li>
                <li>Correo electrónico: <a href ="mailto:administrador@alerasin.com">administrador@alerasin.com</a></li>
            </ul>          
        </div><!-- end useful links -->
         
       <div class="one_five last">        	            
            <h2>Enlaces de interes</h2>              
            <div class="right"><a href="http://www.aaaai.org" target="_blank">Academia americana de alergia, asma e inmunologia<br />
			</a></div>                    
            
            <div class="clearfix divider_line4"></div>

            <div class="right"><a href="http://acaai.org/" target="_blank">The British Society for Allergy & Clinical Immunology</a>
            </div>

            <div class="clearfix divider_line4"></div>

            <div class="right"><a href="http://www.seaic.org/" target="_blank">Sociedad Española de Alergología e Inmunología Clínica </a>
            </div>

            <div class="clearfix divider_line4"></div>

            <div class="right"><a href="http://www.rscmv.org.ve" target="_blank">Red de sociedades científicas médicas venezolanas</a>
            </div>
        
            <div class="clearfix divider_line4"></div>

            <div class="right"><a href="http://www.svaai.org.ve/" target="_blank">Sociedad Venezolana de Alergia, asma e inmunologia</a>
            </div>
        
            <div class="clearfix divider_line4"></div>

            <div class="right"><a href="http://www.anm.org.ve/" target="_blank">Academia Nacional de Medicina</a>
            </div>
  
    </div><!-- end enlaces  -->
	
    <div class="clearfix"></div>
    
</div>

<div class="copyright_info">

    <div class="container">
    
        <div class="one_half">
        
            <b>Copyright © 2015. All rights reserved.  </b>
            
        </div>
    
    	<div class="one_half last">
     		
            <ul class="footer_social_links">
             <!--   <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                <li><a href="#"><i class="fa fa-skype"></i></a></li>
                <li><a href="#"><i class="fa fa-flickr"></i></a></li>
               <li><a href="#"><i class="fa fa-html5"></i></a></li>
                <li><a href="#"><i class="fa fa-youtube"></i></a><li>                
                <li><a href="#"><i class="fa fa-rss"></i></a></li> -->
            </ul>                
    	</div>    
    </div>    
</div><!-- end copyright info -->

<a href="#" class="scrollup">Scroll</a><!-- end scroll to top of the page-->

app/views/shared/_menu.html.erb
<div class="menu_main">
    <div class="joosa top_links">Para citas llamar al: <strong>(0212) 999-01-53 ó (0212) 991-46-20</strong>
</div>
           
<nav id="access" class="access" role="navigation">
  <div id="menu" class="menu">
    <ul id="tiny">
      <li><%= link_to "Inicio", root_path %></li>  

<% if usuario_signed_in? %>
  <%= link_to "Cerrar sesion", destroy_usuario_session_path, method: :delete, :class => 'btn btn-primary'%>
<%else%>
  <% @opcionesMenu.each do |opcion|%>
	<li>

<!--
<li>
<a href="#">Qué es <br>la Alergia? 
<i class="fa fa-angle-down"></i>
</a>
-->

    <%if @opcionesSubMenu[opcion.enlace].length ==0 %>
       <%=link_to opcion.titulo.html_safe, "#" %>
    <%else%>
       <%= link_to((opcion.titulo.html_safe + content_tag(:i, "", :class => "fa fa-angle-down")).html_safe,
             "#") %>
        <ul>
            <%@opcionesSubMenu[opcion.enlace].each do |enlace|%>
              <%if enlace.estado%> 
                <li>                    
                  <%=link_to enlace.titulo.html_safe, contenido_path(enlace.id)%> 
                </li>
              <%end%>
            <%end%>
        </ul>                           
    <%end%>
  </li>
<%end%>


  <li><%=link_to "Ingresar", new_usuario_session_path  %></li>
  <li><%=link_to "Contacto", new_contacto_path  %></li>

<%end%> 
        </ul>

    </div>
</nav>
</div>

app/views/shared/_menu2.html.erb
<nav class="navbar navbar-default" role="navigation">
  <!-- El logotipo y el icono que despliega el menú se agrupan
       para mostrarlos mejor en los dispositivos móviles -->
  <div class="navbar-header">
    
  <!--  <a class="navbar-brand" href="#"> -->
          <div class="logo_main">
              <a href="index.html" id="logo"></a>
          </div>
    
<div class="menu_main">
    <div class="joosa top_links">Para citas llamar al: <strong>(0212) 999-01-53 ó (0212) 991-46-20</strong>
    </div>

  <!-->  </a> </!--> 
  </div>
 
 <button type="button" class="navbar-toggle" data-toggle="collapse"
            data-target=".navbar-ex1-collapse">
      <span class="sr-only">Desplegar navegación</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
  <!-- Agrupar los enlaces de navegación, los formularios y cualquier
       otro elemento que se pueda ocultar al minimizar la barra -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
  
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "Inicio", root_path %></li>  

<% if usuario_signed_in? %>
  <%= link_to "Cerrar sesion", destroy_usuario_session_path, method: :delete, :class => 'btn btn-primary'%>
<%else%>
  <% @opcionesMenu.each do |opcion|%>
  <li>
    <%if @opcionesSubMenu[opcion.enlace].length ==0 %>
       <%=link_to opcion.titulo.html_safe, "#" %>
    <%else%>
         <li class="dropdown">

         <%=link_to "#", :'data-toggle' => 'dropdown', :class => 'dropdown-toggle' do%>
  <%=opcion.titulo.html_safe%> 
  <b class="caret"></b>
<% end %>
              

       <!--
<a href="#" class="dropdown-toggle" data-toggle="dropdown">
          Menú #2 <b class="caret"></b> </a>
       --> 
       
       <ul class="dropdown-menu">
            <%@opcionesSubMenu[opcion.enlace].each do |enlace|%>
              <%if enlace.estado%> 
                <li>                    
                  <%=link_to enlace.titulo.html_safe, contenido_path(enlace.id)%> 
                </li>
              <%end%>
            <%end%>
            <li><a href="http://librosweb.es/ejemplos/bootstrap_3/ejemplo-6-29.html#">Lorem ipsum dolor sit am</a></li>
        </ul>    
      </li>
     <%end%>
    </li>
  <%end%>
  <li><%=link_to "Ingresar", new_usuario_session_path  %></li>
  <li><%=link_to "Contacto", new_contacto_path  %></li>
 <%end%> 


</ul>


    
  </div>
</nav>

app/views/shared/_menu_administracion.html.erb
 <%if current_usuario %>       
    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="navbar-header">               
           <%=image_tag "logo.png", class: "logo"%>
           <a class="navbar-brand" href="index.html"></a>
        </div>
          
        <!-- Top Menu Items -->
    <ul class="nav navbar-right top-nav">

<!-- ADMINISTRACIÓN INICIO -->
<li class="dropdown">
    <%=link_to admin_path do %>
        <i class="fa fa-home"></i>Inicio
    <%end%>
 </li> 
<!-- FIN ADMINISTRACIÓN INICIO -->

<!--ADMINISTRACION CMS -->
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-magic"></i>&nbsp;CMS <b class="caret"></b></a>
  <ul class="dropdown-menu alert-dropdown">
     <li><%=link_to "Menú principal", administrator_menu_nivel0s_path  %></li>
     <li class="divider"></li>
  <% @opcionesMenu.each_with_index do |opcion,i| %>
    <li>
      <%=link_to formatearOpcionMenu(opcion.titulo), administrator_menu_nivel0_menu_nivel1s_path(opcion.id) %>
    </li>
  <%end%>
 
  </ul>
</li>
<!-- FIN ADMINISTRACIÓN CMS -->

<!-- ADMINISTRACIÓN FAQ -->
<li class="dropdown">
     <%=link_to administrator_faqs_path do %>
        <i class="fa fa-question-circle"></i>&nbsp;&nbsp;F.A.Q. </a>
    <%end%>
</li> 
<!-- FIN ADMINISTRACIÓN FAQ -->

<!-- ADMINISTRACIÓN TIPs -->
<li class="dropdown">
     <%=link_to administrator_tips_path do %>
        <i class="fa fa-gratipay"></i>&nbsp;&nbsp;Tips </a>
    <%end%>
</li> 
<!-- FIN ADMINISTRACIÓN TIPs -->



<!-- ADMINISTRACIÓN CARRUSEL -->
<li class="dropdown">
 <%=link_to administrator_configurations_path do %>
        <i class="fa fa-gratipay"></i>&nbsp;&nbsp;Carrucel de imagenes </a>
<%end%>

<!-- FIN ADMINISTRACIÓN CARRUSEL -->

<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-bell"></i>&nbsp;Alertas <b class="caret"></b></a>
  <!--<ul class="dropdown-menu alert-dropdown">
    <li>
      <a href="#">Alert Name <span class="label label-default">Alert Badge</span></a>
    </li>
    <li>
      <a href="#">Alert Name <span class="label label-primary">Alert Badge</span></a>
    </li>
    <li>
      <a href="#">Alert Name <span class="label label-success">Alert Badge</span></a>
    </li>
    <li>
      <a href="#">Alert Name <span class="label label-info">Alert Badge</span></a>
    </li>
    <li>
      <a href="#">Alert Name <span class="label label-warning">Alert Badge</span></a>
    </li>
    <li>
      <a href="#">Alert Name <span class="label label-danger">Alert Badge</span></a>
    </li>
    <li class="divider"></li>
    <li>
      <a href="#">View All</a>
    </li>
  </ul>-->
</li>

<li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i>
    <% if current_usuario.rol == 1%>
		Dr(a).
	<%end%>
		<%=current_usuario.nombre + "  "+ current_usuario.apellido%>		
    <b class="caret"></b></a>
    <ul class="dropdown-menu">
	    <li>
	        <%=link_to edit_usuario_registration_path do %>
	        	<i class="fa fa-fw fa-user-md"></i>Datos personales
	    	<%end%>
	    </li>
	    <li>
	        <%=link_to edit_usuario_path do %>
	        	<i class="fa fa-fw fa-key"></i>Datos de acceso
	    	<%end%>
	    </li>
	    <li class="divider"></li>
	    <!--<li>
	    	<a href="#"><i class="fa fa-fw fa-gears"></i> Configuración</a>
	    </li>
	    <li class="divider"></li>-->
	    <li>
	        <%= link_to "Cerrar sesion", destroy_usuario_session_path, method: :delete, :class => 'btn btn-primary'%>
	    </li>
    </ul>
</li>
</ul>
</nav>
<%else%>
Usted no está logeado
<%end%>

app/views/shared/_menu_paciente.html.erb
     
    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="navbar-header">               
           <%=image_tag "logo.png", class: "logo"%>
           <a class="navbar-brand" href="index.html"></a>
        </div>
          
        <!-- Top Menu Items -->
    <ul class="nav navbar-right top-nav">


<li class="dropdown">
    <%=link_to admin_path do %>
        <i class="fa fa-home"></i>Inicio
    <%end%>
 </li> 

<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-magic"></i>Menu 1 <b class="caret"></b></a>
  <ul class="dropdown-menu alert-dropdown">
     <li><%=link_to "Sub opción 1", ejemplo1_path  %></li>
     <li class="divider"></li>
      <li><%=link_to "Sub opción 1", ejemplo1_path  %></li>
     <li class="divider"></li>
      <li><%=link_to "Sub opción 1", ejemplo1_path  %></li>
     <li class="divider"></li>
      <li><%=link_to "Sub opción 1", ejemplo1_path  %></li>
     <li class="divider"></li>
      <li><%=link_to "Sub opción 1", ejemplo1_path  %></li>
     <li class="divider"></li>
  </ul>
</li>

<li class="dropdown">
     <%=link_to ejemplo1_path do %>
        <i class="fa fa-gratipay"></i>&nbsp;&nbsp;Opción 2</a>
    <%end%>
   
</li> 

<li class="dropdown">
    <%=link_to ejemplo1_path do %>
        <i class="fa fa-gratipay"></i>&nbsp;&nbsp;Opción 3 </a>
    <%end%>
</li> 

<li class="dropdown">
 <%=link_to ejemplo1_path do %>
        <i class="fa fa-gratipay"></i>&nbsp;&nbsp;Opción 3 </a>
<%end%>

<li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i>
    <% if current_usuario.rol == 1%>
    Dr(a).
  <%end%>
    <%=current_usuario.nombre + "  "+ current_usuario.apellido%>    
    <b class="caret"></b></a>
    <ul class="dropdown-menu">
      <li>
          <%=link_to edit_usuario_registration_path do %>
            <i class="fa fa-fw fa-user-md"></i>Datos personales
        <%end%>
      </li>
      <li>
          <%=link_to edit_usuario_path do %>
            <i class="fa fa-fw fa-key"></i>Datos de acceso
        <%end%>
      </li>
      <li class="divider"></li>
      <li>
          <%= link_to "Cerrar sesion", destroy_usuario_session_path, method: :delete, :class => 'btn btn-primary'%>
      </li>
    </ul>
</li>
</ul>
</nav>

app/views/shared/_menu_tratamiento.html.erb
 <%if current_usuario %>       
    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="navbar-header">               
           <%=image_tag "logo.png", class: "logo"%>
           <a class="navbar-brand" href="index.html"></a>
        </div>
          
        <!-- Top Menu Items -->
    <ul class="nav navbar-right top-nav">

<!-- ADMINISTRACIÓN INICIO -->
<li class="dropdown">
    <%=link_to admin_path do %>
        <i class="fa fa-home"></i>&nbsp;Inicio
    <%end%>
 </li> 
<!-- FIN ADMINISTRACIÓN INICIO -->


<!-- ADMINISTRACIÓN USUARIOS -->
<li class="dropdown">
     <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-male"></i><i class="fa fa-female"></i>&nbsp;Administrar pacientes <b class="caret"></b></a>
     <ul class="dropdown-menu alert-dropdown">
		  <li>
  		  <%=link_to "Agregar Paciente", new_usuario_registration_path %>
      </li>

    	<li>
       <%=link_to "Actualización de datos", buscar_administrator_pacientes_path%>
      </li>

      <li>      
      <%=link_to "Registro de pruebas alergicas", new_usuario_registration_path %>
    	</li>
    	
      <li>
        <%=link_to "Listado de pacientes", usuarios_list_path%>
      </li>

 </ul>   	
</li> 
<!-- FIN ADMINISTRACIÓN USUARIOS -->

<!-- ADMINISTRACIÓN CONTROL DE VACUNAS -->
<li class="dropdown">
     <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-magic"></i>&nbsp;Vacunas <b class="caret"></b></a>
     <ul class="dropdown-menu alert-dropdown">
		<!--li>
      Registro de pago de vacuna
    	</li>
      <li>
      Pagos realizados
    	</li>	
    	<li>
      Solicitud vacuna
    	</li>
    	<li>
      Control de vacunas entregadas
    	</li!-->
      <li>
      <%=link_to "Cambio de estado de frasco", frascos_no_retirados_path%>       
      </li>
    	<li>
      <%=link_to "Eliminación de vacunas preparadas", frascos_eliminar_path%>       
    	</li>
    	<!--li>
      Vacunas solicitadas
    	</li!-->
    	<li>
      <%=link_to "Control de vacunas preparadas", frascos_path%>
    	</li>
      <li>
      <%=link_to "Lista de vacunas entregadas", frascos_entregados_path%>    
    	</li>	

 </ul>   	
</li> 

<!-- FIN ADMINISTRACIÓN CONTROL DE VACUNAS -->

<!-- ADMINISTRACIÓN CONTROL DE ARCHIVOS -->

<li class="dropdown">
     <%=link_to administrator_tips_path do %>
        <i class="fa fa-files-o"></i>&nbsp;&nbsp;Archivos </a>
    <%end%>
</li> 
<!-- FIN ADMINISTRACIÓN CONTROL DE ARCHIVOS -->


<!-- FIN ADMINISTRACIÓN CARRUSEL -->

<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-bell"></i>&nbsp;Alertas <b class="caret"></b></a>
</li>


<li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i>
      <%puts "currento2"%>
    <% if current_usuario.rol == 1 || current_usuario.rol == 2%>
		Dr(a).
	<%end%>
		<%=current_usuario.nombre + "  "+ current_usuario.apellido%>		
    <b class="caret"></b></a>
    <ul class="dropdown-menu">
	    <li>
	        <%=link_to edit_usuario_registration_path do %>
	        	<i class="fa fa-fw fa-user-md"></i>Datos personales
	    	<%end%>
	    </li>
	    <li>
	        <%=link_to edit_usuario_password_path do %>
	        	<i class="fa fa-fw fa-key"></i>Datos de acceso
	    	<%end%>
	    </li>
	    <li class="divider"></li>
	    <!--<li>
	    	<a href="#"><i class="fa fa-fw fa-gears"></i> Configuración</a>
	    </li>
	    <li class="divider"></li>-->
	    <li>
	        <%= link_to "Cerrar sesion", destroy_usuario_session_path, method: :delete, :class => 'btn btn-primary'%>
	    </li>
    </ul>
</li>
</ul>
</nav>
<%else%>
Usted no está logeado
<%end%>
   

app/views/shared/_secciones.html.erb
<div class="joosa fusectio4">
<div class="clearfix mar_top2"></div>
   <div class="container">
     
     


      <!-- end news section -->
      <div class="one_third last" id="ultima-seccion">
         <h4 style = "height:35px" align="center"><strong>pacientes en tratamiento desensibilizante de alergia</strong></h3>
         <div class="spe_banner">
            <div class="left"></div>
            <div class="right">
               <p>Solo para pacientes en tratamiento desensibilizante.</p>
               <%=link_to "Ingresar aquí", new_usuario_session_path  %>
            </div>
         </div>
      </div>
      <!-- end banner section -->
   </div>
</div>
<!-- end features section 4 -->
<!-- FIN SECCIONES 
   ======================-->